/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.switch_application.gui;

import com.mycompany.switch_application.connection.Servidor;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author sergi
 */
public class UnicastGui extends javax.swing.JFrame {

    /**
     * Creates new form UnicastGui
     */
    private HashMap<String, String> tablaArp;
    private Servidor servidor;

    public UnicastGui(HashMap<String, String> tablaArp, Servidor servidor) {
        this.tablaArp = tablaArp;
        this.servidor = servidor;
        initComponents();
        lblStatusPaquete.setText("");
        generateItemsCombo();
    }

    private void generateItemsCombo() {
        // Obtener las claves (direcciones MAC) de la tabla ARP
        Set<String> macAddresses = tablaArp.keySet();

        // Convertir las claves en una lista para poder agregarlas al ComboBox
        List<String> macAddressList = new ArrayList<>(macAddresses);

        // Crear un modelo para el ComboBox y agregar las direcciones MAC
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(macAddressList.toArray(new String[0]));
        cmbArp.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbArp = new javax.swing.JComboBox<>();
        btnSendPackage = new javax.swing.JButton();
        lblStatusPaquete = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Unicast");

        cmbArp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSendPackage.setText("Enviar Paquete");
        btnSendPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendPackageActionPerformed(evt);
            }
        });

        lblStatusPaquete.setText("jLabel2");

        jLabel2.setText("Mac");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnSendPackage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatusPaquete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbArp, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbArp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(btnSendPackage)
                .addGap(18, 18, 18)
                .addComponent(lblStatusPaquete)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendPackageActionPerformed
        // Obtener el item seleccionado en el combobox
        String selectedMac = (String) cmbArp.getSelectedItem();
        String result = servidor.unicast(selectedMac);
        lblStatusPaquete.setText(result);
    }//GEN-LAST:event_btnSendPackageActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendPackage;
    private javax.swing.JComboBox<String> cmbArp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblStatusPaquete;
    // End of variables declaration//GEN-END:variables
}
